server:
  port: 8765

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.38:8080/realms/pisio
          jwk-set-uri: http://keycloak:8080/realms/pisio/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
